export const rooms = [
 {id:'content',name:'Tiger Pounce',short:'Content',host:'Aditi',role:'The story challenger',icon:'Clapperboard',color:'#f6b29f',x:22,y:25,tag:'Make them stop scrolling.',intro:'A blank page is a good place to start. What’s the idea you can’t stop thinking about?',prompts:['A YouTube series with a twist','An idea for my next article'],lens:'audience, hook, format, repeatability'},
 {id:'technical',name:'Falcon Flight',short:'Technical',host:'Ananya',role:'The systems thinker',icon:'Code2',color:'#a9d9bf',x:49,y:25,tag:'Find the problem worth building for.',intro:'Before we write a single line: what problem do you want to make disappear, and for whom?',prompts:['An AI tool people actually need','Turn my side project into a product'],lens:'user pain, alternatives, constraints, smallest test'},
 {id:'sports',name:'Cheetah Sprint',short:'Sports',host:'Dhruv',role:'The armchair challenger',icon:'Flag',color:'#a8c9ef',x:77,y:25,tag:'Beyond the final whistle.',intro:'Race weekend or match day? Pitch me the idea a real fan would come back for.',prompts:['An F1 race-weekend experience','A football community idea'],lens:'fan identity, access, seasonality, differentiation'},
 {id:'fashion',name:'Peacock Strut',short:'Fashion',host:'Sanya',role:'The taste interrogator',icon:'Scissors',color:'#ecb3d2',x:22,y:51,tag:'Good taste needs a point of view.',intro:'Tell me what you want to put into the world. Who wears it, and what does it say about them?',prompts:['A streetwear concept','A personal styling experience'],lens:'identity, audience, sourcing, price'},
 {id:'travel',name:'Elephant Ramble',short:'Travel',host:'Aarav',role:'The curious explorer',icon:'Compass',color:'#e6c895',x:77,y:51,tag:'Take the road with a reason.',intro:'Where are we going with this? Tell me the travel experience you wish existed.',prompts:['Help travellers find hidden places','A slow-travel community'],lens:'traveller type, local access, feasibility, trust'},
 {id:'gaming',name:'Fox Leap',short:'Gaming & Anime',host:'Kriti',role:'The fandom insider',icon:'Gamepad2',color:'#c4b0f0',x:27,y:77,tag:'Build something fans live in.',intro:'Every great fandom has its own language. Which community is this for, and what are they missing?',prompts:['An anime discovery experience','A game my friends would replay'],lens:'community rituals, core loop, originality, retention'},
 {id:'music',name:'Dolphin Glide',short:'Music',host:'Mihir',role:'The sound scout',icon:'Headphones',color:'#ebce83',x:72,y:77,tag:'Find the idea with a pulse.',intro:'What are you hearing that everyone else is missing? Tell me your music idea.',prompts:['A music discovery concept','A community for independent artists'],lens:'listener niche, discovery, artist value, rights'},
] as const;
export type Room = typeof rooms[number];
export type Message = {role:'user'|'assistant';content:string;speaker?:string;memberId?:string;target?:string;id?:string;replyTo?:string;replyToName?:string};
